-- Crear la tabla cliente
CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    correo VARCHAR(255) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- Insertar datos iniciales
INSERT INTO cliente (nombre, correo) VALUES
('Juan Pérez', 'juan.perez@example.com'),
('María López', 'maria.lopez@example.com'),
('Carlos Martínez', 'carlos.martinez@example.com');
